application-description: @project.description@
application-version: @project.version@

spring:
  data:
    mongodb:
      uri: ${env.MONGO_DB_URI}
      database: ${env.MONGO_DB_DATABASE}
jwt:
  secret: ${env.JWT_SECRET}
  expirationDateInMs: ${env.JWT_EXPIRATION_IN_MS}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

springdoc:
  use-fqn: true
