name: Release - Test, Build & Redeploy
on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  pipeline:
    name: Build, Test & Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Binance-Java-Api
        run: |
          git clone https://github.com/brunnooliveira/binance-java-api.git
          cd binance-java-api
          mvn clean install -DskipTests

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Maven Package
        run: mvn -B clean package -DskipTests

      - name: Maven Verify
        run: mvn -B clean verify

      - name: Where we are?
        run: |
          pwd
          ls -la src/main/resources

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest -t ${{ secrets.DOCKER_REPO }}:${GITHUB_SHA::8} .

      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}