name: Release - Test, Build & Redeploy
on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  pipeline:
    name: Build, Test & Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Binance-Java-Api
        uses: actions/checkout@v2
        with:
          repository: brunnooliveira/binance-java-api
          ref: master

      - name: Where we are?
        run: |
          pwd
          ls -la

#      - name: Maven Install Binance Java Api
#          run: mvn -B clean package -DskipTests

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4

      - name: Maven Package
        run: mvn -B clean package -DskipTests

      - name: Maven Verify
        run: mvn -B clean verify